# -------------------------
# Global configuration
# -------------------------
StylesPath = styles
MinAlertLevel = suggestion
Packages = Microsoft, write-good

# -------------------------
# Markdown rules
# -------------------------
[*.md]
BasedOnStyles = Microsoft, write-good
