name: Deploy Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcairo2 \
            libpango-1.0-0 \
            libgdk-pixbuf2.0-0

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-with-pdf weasyprint

      - name: Build documentation
        env:
          ENABLE_PDF_EXPORT: 1
        run: mkdocs build

      - name: Deploy site
        run: mkdocs gh-deploy --force
