site_name: Docs as Code Portfolio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - content.code.copy
    - content.action.edit
    - search.highlight

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
plugins:
  - search
  - with-pdf:
      cover: true
      cover_title: Docs-as-Code Portfolio
      cover_subtitle: Technical Documentation
      toc_level: 2
      output_path: pdf/docs-as-code.pdf